#!/usr/bin/env python3
"""Generate docs/REFERENCE.md from canonical JSON configuration."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "REFERENCE.md"


def load(path: str) -> dict:
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def render() -> str:
    models = load("config/models.json")
    upstreams = load("integrations/upstreams.lock.json")["upstreams"]
    extensions = load("pi/extensions.json")["profiles"]
    skills = load("pi/skills.json")["profiles"]

    lines = [
        "# Generated Reference",
        "",
        "> Generated by `scripts/generate-reference.py`. Do not edit manually.",
        "",
        "## Model roles",
        "",
        "### Copilot",
        "",
        "| Role | Model |",
        "|---|---|",
    ]
    for role, spec in models["copilot"].items():
        lines.append(f"| `{role}` | `{spec['model']}` |")

    lines += ["", "### Claude Code", "", "| Role | Model | Effort |", "|---|---|---|"]
    for role, spec in models["claude_code"].items():
        lines.append(f"| `{role}` | `{spec['model']}` | `{spec.get('effort') or ''}` |")

    lines += [
        "",
        "## Tracked upstreams",
        "",
        "| Integration | Repository | Ref | Locked commit | Mode |",
        "|---|---|---|---|---|",
    ]
    for item in upstreams:
        lines.append(
            f"| `{item['name']}` | `{item['repository']}` | `{item['ref']}` | "
            f"`{item['commit'][:12]}` | `{item['mode']}` |"
        )

    lines += ["", "## Pi extension profiles"]
    for profile, packages in extensions.items():
        lines += ["", f"### `{profile}`", ""]
        lines += [f"- `{package}`" for package in packages]

    lines += ["", "## Curated Pi skill profiles"]
    for profile, names in skills.items():
        lines += ["", f"### `{profile}`", ""]
        lines += [f"- `{name}`" for name in names]

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"stale generated file: {OUTPUT.relative_to(ROOT)}")
            return 1
        print("generated reference is current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
